#
# BTstack example 'sm_pairing_peripheral' for ESP32 port
#
# Generated by /home/sacha/Projets/Arduino/Lolin32/btstack/port/esp32
# On Sun Feb 25 14:30:12 2018

PROJECT_NAME := sm_pairing_peripheral

include $(IDF_PATH)/make/project.mk
